name: Create release and publish container image

on:
  push:
    tags:
      - 'release/*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -r requirements.txt

      - name: Build distribution
        run: python -m build

      - uses: docker/setup-buildx-action@v3

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SCALEWAY_REGISTRY_ENDPOINT }}
          username: nologin
          password: ${{ secrets.SCALEWAY_API_KEY }}

      - name: Read version from file
        id: read_version
        run: echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.SCALEWAY_REGISTRY_ENDPOINT }}/traffic-data-domain-updater:${{ steps.read_version.outputs.version }}
            ${{ secrets.SCALEWAY_REGISTRY_ENDPOINT }}/traffic-data-domain-updater:latest
          build-args: VERSION=${{ steps.read_version.outputs.version }}
